[project]
name = "vschess"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "chess>=1.11.2",
    "fastapi>=0.111.0",
    "pydantic>=2.12.3",
    "uvicorn>=0.30.0",
]
